INSERT INTO control_families (family_id, name) VALUES ('AC', 'ACCESS CONTROL');
INSERT INTO control_families (family_id, name) VALUES ('AT', 'AWARENESS AND TRAINING');
INSERT INTO control_families (family_id, name) VALUES ('AU', 'AUDIT AND ACCOUNTABILITY');
INSERT INTO control_families (family_id, name) VALUES ('CA', 'ASSESSMENT, AUTHORIZATION, AND MONITORING');
INSERT INTO control_families (family_id, name) VALUES ('CM', 'CONFIGURATION MANAGEMENT');
INSERT INTO control_families (family_id, name) VALUES ('CP', 'CONTINGENCY PLANNING');
INSERT INTO control_families (family_id, name) VALUES ('IA', 'IDENTIFICATION AND AUTHENTICATION');
INSERT INTO control_families (family_id, name) VALUES ('IR', 'INCIDENT RESPONSE');
INSERT INTO control_families (family_id, name) VALUES ('MA', 'MAINTENANCE');
INSERT INTO control_families (family_id, name) VALUES ('MP', 'MEDIA PROTECTION');
INSERT INTO control_families (family_id, name) VALUES ('PE', 'PHYSICAL AND ENVIRONMENTAL PROTECTION');
INSERT INTO control_families (family_id, name) VALUES ('PL', 'PLANNING');
INSERT INTO control_families (family_id, name) VALUES ('PM', 'PROGRAM MANAGEMENT');
INSERT INTO control_families (family_id, name) VALUES ('PS', 'PERSONNEL SECURITY');
INSERT INTO control_families (family_id, name) VALUES ('RA', 'RISK ASSESSMENT');
INSERT INTO control_families (family_id, name) VALUES ('SA', 'SYSTEM AND SERVICES ACQUISITION');
INSERT INTO control_families (family_id, name) VALUES ('SC', 'SYSTEM AND COMMUNICATIONS PROTECTION');
INSERT INTO control_families (family_id, name) VALUES ('SI', 'SYSTEM AND INFORMATION INTEGRITY');
INSERT INTO control_families (family_id, name) VALUES ('SR', 'SUPPLY CHAIN RISK MANAGEMENT');
