image:
  file: .gitpod.Dockerfile

ports:
  - port: 8080  # Spring Boot app default port
    onOpen: open-preview
  - port: 5432  # PostgreSQL port


# init:     Runs only once when the workspace is created, 
#            which will initialize the PostgreSQL Docker container.
# command:  Runs every time the workspace starts, 
#           which will start the container if it exists (after stopping or a session pause).
tasks:
  - name: Start PostgreSQL Docker container
    init: docker run --name postgres -e POSTGRES_USER=postgres -e POSTGRES_PASSWORD=password -e POSTGRES_DB=compliance_tracker -p 5432:5432 -d postgres
    command: docker start postgres